// Aviasales_Project/aviasales_react_redux_saga/src/components/ticket/index.js
import React from 'react';

import Segment from '../segment'
// import { connect } from 'react-redux';

import style from './style.module.css'

class Ticket extends React.Component {



    // componentDidMount() {
    //     this.props.setSearchId();
    // }

    price(price){
        return String(price).replace(/(\d)(?=(\d\d\d)+([^\d]|$))/g, '$1 ');
    }

    render() {
        return (
            <div className={style.ticket}>
                <div className={style.header}> 
                        <div className={style.price}>{this.price(this.props.ticket.price)} р</div>
                        <img src={`//pics.avs.io/99/36/${this.props.ticket.carrier}.png`} alt="sorry" className={style.logo} />
                </div>
                <div className={style.segment}>
                    <Segment segm={this.props.ticket.segments[0]}></Segment>
                </div>
                <div className={style.segment}>
                    <Segment segm={this.props.ticket.segments[1]}></Segment>
                </div>
            </div>

        );

    }
}

// *до використання селекторів
// const mapStateToProps = state => {
//     ///// !state.tickets.tiсkets/* .length>0 */?console.log(state.tickets.tiсkets[0], "state o props"):console.log(state.tickets.tickets, "state null");
//     console.log(state.tickets.tickets.length>0?( state.tickets.tickets[0]): 0 ,"mapStateToProps");
//     return {
//         tick: (state.tickets.tickets.length>0?( state.tickets.tickets[0]): null),
        
//     };
// };

export default Ticket;

// export default connect( mapStateToProps, /*null,*/ /* { setSearchId } */)(Ticket);

// Aviasales_Project/aviasales_vue/src/components/Ticket.vue
<template>
    <div :class="$style.ticket">
        <div :class="$style.header">
            <div :class="$style.price">{{price}} P</div>
            <img alt="sorry" :src="`//pics.avs.io/99/36/${tick.carrier}.png`" :class="$style.logo">
        </div>
        <div :class="$style.segment">
            <Segment :segm= tick.segments[0]></Segment>
        </div>
        <div :class="$style.segment">
            <Segment :segm= tick.segments[1]></Segment>
        </div>
    </div>
</template>

<script>
    import Segment from "./Segment";
    export default {
        name: 'ticket',
        components: {
            Segment,
        },
        props: {
            tick: {
                type: Object,
                default: function () {
                    return { segments: [
                            {}, {}
                        ]
                    }
                }
            },
        },
        computed: {
            price(){
                if (!this.tick) {
                    return;
                }
                return String(this.tick.price).replace(/(\d)(?=(\d\d\d)+([^\d]|$))/g, '$1 ');
            },
        }
    }
</script>

<style lang="less" scoped module>
    .ticket{
        display: flex;
        flex-direction: column;
        /* margin: 20px; */
        background-color: white;
        box-sizing: border-box;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);

        font-family: 'Open Sans', sans-serif;
        font-style: normal;
        font-weight: 600;

        text-transform: uppercase;

        // margin-top: 20px;
    }

    .header{
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
        margin: 20px 30px 20px 20px;
    }

    .price {
        font-size: 24px;
        line-height: 24px;
        color: #2196F3;
    }

    .segment{
        margin: 0 20px 20px 20px;
    }
</style>
