// Aviasales_Project/aviasales_vue/src/components/Segment.vue
<template>
    <div :class="$style.segment">
        <div :class="$style.segmentBlock">
            <div :class="$style.title">{{segm.origin}} - {{segm.destination}}</div>
            <div :class="$style.value">{{flightTime}}</div>
        </div>
        <div :class="$style.segmentBlock">
            <div :class="$style.title">В дорозі</div>
            <div :class="$style.value">{{Math.round(segm.duration/60, 0)}}ч {{Math.round(segm.duration%60, 0)}}м</div>
        </div>
        <div :class="$style.segmentBlock">
            <div :class="$style.title">{{transfers}} </div>
            <div :class="$style.value">
                <div
                    v-for="stop in segm.stops"
                    :key="stop">{{stop}}</div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "Segment",
        props: {
            segm: Object,
            default: {},
        },
        computed: {
            transfers(){
                if (!this.segm.stops) {
                    return "0 пересадок";
                }
                return `${this.segm.stops.length} пересадки`;
            },
            flightTime(){
                const date = new Date(this.segm.date);
                const dateArrival = new Date(this.segm.date);
                dateArrival.setUTCMinutes(dateArrival.getMinutes() + this.segm.duration);

                return `${setTimeStr(date.getHours())}:${setTimeStr(date.getMinutes())} - ${setTimeStr(dateArrival.getHours())}:${setTimeStr(dateArrival.getMinutes())}`;
            }
        }
    }

    function setTimeStr(timeVal){
        return timeVal<10? `0${timeVal}`: `${timeVal}`;
    }
</script>

<style module>
    .segment{
        /* font-family: "Open Sans", sans-serif;
        text-transform: uppercase; */
        display: flex;
        justify-content: space-between;

    }

    .segmentBlock{
        text-align: start;
    }


    .title{

        font-size: 12px;
        line-height: 18px;

        letter-spacing: 0.5px;

        color: #A0B0B9;

    }

    .value{
        font-size: 14px;
        line-height: 21px;
        color: #4A4A4A;

        display: flex;
        flex-direction: row;
        justify-content: flex-start;
    }

    .value div:not(:last-child):after {
        content: ', ';
        margin-right: 5px;
    }
</style>

// Aviasales_Project/aviasales_react_redux_saga/src/components/segment/index.js
import React from 'react';

import style from './style.module.css'

class Segment extends React.Component {

    flightTime(date, duration){
        const dateClg = new Date(date);
        const dateArrival = new Date(date);
        dateArrival.setUTCMinutes(dateArrival.getMinutes() + duration);

        return `${this.setTimeStr(dateClg.getHours())}:${this.setTimeStr(dateClg.getMinutes())} - ${this.setTimeStr(dateArrival.getHours())}:${this.setTimeStr(dateArrival.getMinutes())}`;
    }

    setTimeStr(timeVal){
        return timeVal<10? `0${timeVal}`: `${timeVal}`;
    }

    transfers(stops){
        return `${stops.length} пересадки`;
    }

    render() {

        return (

            <div className={style.segment}>
                    <div className={style.segmentBlock}>
                            <div className={style.title}> {this.props.segm.origin} - {this.props.segm.destination}</div>
                            <div className={style.value}>{this.flightTime(this.props.segm.date, this.props.segm.duration)}</div>
                    </div>
                    <div className={style.segmentBlock}>
                            <div className={style.title}>В дорозі</div>
                            <div className={style.value}>{Math.round(this.props.segm.duration/60, 0)}ч {Math.round(this.props.segm.duration%60, 0)}м</div>
                    </div>
                    <div className={style.segmentBlock}>
                            <div className={style.title}>{this.transfers(this.props.segm.stops)}</div>
                            <div className={style.value} >
                                {this.props.segm.stops.map(item => {
                                    return <div key={item}>{item}</div>
                                })}
                            </div>
                    </div>

            </div>


        );

    }
}



export default Segment;
